### ISSUE TITLE
ProcedureRequest subject Reference lists "Patient\test"

### ISSUE THREAD

**Issue by mhiner** [amida-tech/cda-fhir#8]
ProcedureRequest subject Reference does not list a valid PatientID (Hapi accepts this and saves it as sent but I believe we want the value to be the patient ID.)

**Comment by chaldon** [comment]
I modified the last bundle so it creates/updates Patient/test, so Patient/test become a valid id. The idea behind this behavior is that we suppose to know who is uploading data (user login "test") and we can create/associate it with Patient/test
